### ISSUE TITLE
How to use graphite_exporter when the cluster cannot connect to the network?

### ISSUE THREAD

**Issue by NoSadness** [prometheus/graphite_exporter#101]
![Uploading make.png…]()

**Comment by matthiasr** [comment]
I'm not sure what you mean, your screenshot did not upload? Are you trying to build the exporter in an isolated environment?

**Comment by NoSadness** [comment]
![make](https://user-images.githubusercontent.com/18392439/60225704-74a7be00-98ba-11e9-920c-95e1cdad4aaf.png)
yes,I want to build the exporter in an isolated environment,but make command failed.

**Comment by matthiasr** [comment]
The build-and-test system assumes that it can download some tools (linters etc.) from the internet. This is the general Prometheus build system, not statsd exporter specific. The assumption is that you build in an environment that can do this, and then transfer the compiled binaries into the closed-off environment.

If you really want to build without internet access, you are somewhat on your own – in principle, the basic build should work since we vendor the dependencies of the exporter itself. You may be able to run specific make targets; you may be better off just invoking `go build` yourself.

This is not something that I can or want to support as an official feature of the build system, so I'm going to close this issue. For usage questions, please see the [community page](https://prometheus.io/community/).

**Comment by NoSadness** [comment]
Thank you for all your assistance. I am researching how to solve this problem.
