### ISSUE TITLE
Hadoop metrics with space in them

### ISSUE THREAD

**Issue by zefir6** [prometheus/graphite_exporter#112]
I am trying to use graphite exporter to get Cloudera Hadoop metrics into prometheus.
The issue I am having is with spaces in the metric name.

This is my rule:
```
- match: 'cdh\.dfs\.FSNamesystem\.Context=([a-zA-Z]+)\.(?:EnabledEcPolicies=(?:[A-Za-z0-9-]+)\.)?(?:HAState=(?:\S+)\.)?(?:TotalSyncTimes=(?:[\d ]+)\.)?Hostname=([0-9a-z._]+com)\.(\S+)'
  name: "cdh_dfs_FSNamesystem_${3}"
  match_type: regex
  labels:
    context: "$1"
    hostname: "$2"
```

But I am getting multiple errors like this:
```
Dec 17 14:36:39 <redacted hostname> graphite_exporter[2994459]: time="2019-12-17T14:36:39+01:00" level=info msg="Invalid part count of 5 in line: cdh.dfs.FSNamesystem.Context=dfs.EnabledEcPolicies=RS-6-3-1024k.HAState=active.TotalSyncTimes=3 3 .Hostname=<redacted hostname>.TotalSyncCount 1 1576589798" source="main.go:122"
Dec 17 14:36:49 r<redacted hostname> graphite_exporter[2994459]: time="2019-12-17T14:36:48+01:00" level=info msg="Invalid part count of 5 in line: cdh.dfs.FSNamesystem.Context=dfs.EnabledEcPolicies=RS-6-3-1024k.HAState=active.TotalSyncTimes=18 41 .Hostname=r<redacted hostname>.TotalSyncCount 6 1576589808" source="main.go:122"
Dec 17 14:36:59 <redacted hostname> graphite_exporter[2994459]: time="2019-12-17T14:36:58+01:00" level=info msg="Invalid part count of 5 in line: cdh.dfs.FSNamesystem.Context=dfs.EnabledEcPolicies=RS-6-3-1024k.HAState=active.TotalSyncTimes=18 41 .Hostname=<redacted hostname>.TotalSyncCount 6 1576589818" source="main.go:122"
```

Is there any way to remove those whitespaces while processing before regexp? As this seems to happen before remapping is done.

**Comment by matthiasr** [comment]
I can't find a definite source of "what is valid in the Graphite line protocol" but I don't think a varying number of spaces are part of the [protocol](https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-3-understanding-the-graphite-message-format). https://github.com/dropwizard/metrics/issues/637 is also discussing a few different acceptable character sets, none of which include spaces.

I think the problem is that there are multiple layers of translation here, from Hadoop metrics to Graphite to Prometheus. All of these have mismatched data models. It looks like your lines even include multiple values at once: A metric component like `TotalSyncCount 6 1576589818` is not going to work well in Prometheus.

I would strongly recommend to find a different way to expose these metrics to Prometheus, e.g. via JMX. [These example configurations](https://github.com/fahlke/jmx_exporter-cloudera-hadoop) look promising.
