### ISSUE TITLE
Graphite_exporter: Writing metric on port 9109 over TCP failing

### ISSUE THREAD

**Issue by digambarGitHub** [prometheus/graphite_exporter#41]
My application is sending metrics over tcp on port 9109 in plaintext protocol format :
<metric path> <metric value> <metric timestamp>

I am using method writeBytes() of class **DataOutputStream** to write data on graphite_exporter's 9109 port. There is writing successfully but can not see data on http://localhost:9108/metrics. 

Before sending data I have started graphite_exporter to listen on port 9108. 
Can someone has any idea why I can not see my metrics on http://localhost:9108/metrics?

**Comment by matthiasr** [comment]
What mapping configuration are you using? Do the basic examples [here](https://github.com/prometheus/graphite_exporter#usage) work? Is there anything in the exporter logs about this?

**Comment by digambarGitHub** [comment]
I have metrics kind of : _servers.usva.instance1.cpu.total.user_

Configuration is as file looks like : 
servers.*.*.cpu.total.user
name="servers_cpu_percent"
region="$1"
instance="$2"
job="cpu_job"

Exporter logs stay as it is like : 
![image](https://user-images.githubusercontent.com/8347565/36382336-91555322-15ae-11e8-9baf-663b7a04f352.png)

**Comment by matthiasr** [comment]
I think the mapping does not match, and therefore the metrics are discarded. Try with

```
servers.*.*.cpu.total.user
```

instead? In general, to exclude problems with the mapping, try without the mapping, the metrics should show up even if they're not in a great format.

More long-term, consider using [node exporter](https://github.com/prometheus/node_exporter) or [WMI exporter](https://github.com/martinlindhe/wmi_exporter) to collect CPU utilization metrics. Going through the graphite exporter should be a last resort, if no more native option to get the data you want in Prometheus format is available.

I'll close this issue, since it does not appear to be an issue with the exporter itself. For usage questions, it's better to use the [appropriate channels](https://prometheus.io/community/) where there are more eyes on the problem.

**Comment by digambarGitHub** [comment]
I have the metrics as you shown servers.*.*.cpu.total.user

**Comment by matthiasr** [comment]
Could you attach the mappings file as it is here?

**Comment by digambarGitHub** [comment]
Here is the file:

**Comment by digambarGitHub** [comment]
Here is the file :
[graphite_mapping.txt] (https://github.com/prometheus/graphite_exporter/files/1738955/graphite_mapping.txt)

**Comment by digambarGitHub** [comment]
@matthiasr  : issue is resolved, I was sending timestamp 6 hours back. we need to send latest timestamp.

Btw how long back timestamp works for graphite exporter?

**Comment by matthiasr** [comment]
Anything less than the value of the --graphite.sample-expiry flag should work, by default 5 minutes.

Keep in mind that Prometheus does not ingest old samples the way graphite does. Sending anything older than "now" will most likely not do what you expect.
